/**
 * Generated by tsnapi — public API snapshot of `dsh-pet-component`
 */
// #region Interfaces
export interface Category {
  id: string;
  weight: number;
  noMirror?: boolean;
  actions: string[];
}
export interface CodexPetConfig {
  id?: string;
  displayName?: string;
  description?: string;
  spriteVersionNumber?: 1 | 2;
  spritesheetPath?: string;
  columns?: number;
  frameWidth?: number;
  frameHeight?: number;
  rows?: number;
  size?: number;
  motions?: Partial<Record<PetRenderMotion, number | CodexPetFrameSpec>>;
}
export interface CodexPetFrameSpec {
  row: number;
  frames?: number;
  interval?: number;
  durations?: number[];
  loop?: boolean;
}
export interface DshPetAnimations {
  idle?: string[];
  turn?: string[];
  drag?: string[];
  clicks?: string[];
  moves?: MovesConfig;
  categories?: Category[];
  events?: PetEvents;
  motions?: Partial<Record<PetRenderMotion, AnimationSlot>>;
}
export interface DshPetConfig {
  motions?: Partial<Record<PetRenderMotion, AnimationSlot>>;
  animations?: DshPetAnimations;
  animationWeights?: Partial<PetWeights>;
  eventsRefreshSec?: Record<string, number>;
  physics?: Partial<PhysicsParams>;
  pets?: DshPetEntry[];
  size?: number;
  whisperPrompt?: string;
  chatMemoryRounds?: number;
  whisperImageEnabled?: boolean;
  chatImageEnabled?: boolean;
  memes?: Record<string, string>;
  notificationsEnabled?: boolean;
}
export interface DshPetEntry {
  id: string;
  name?: string;
  size?: number;
  balanceEnabled?: boolean;
  whisperEnabled?: boolean;
  workStatusEnabled?: boolean;
  eventsRefreshSec?: Record<string, number>;
  display?: PetDisplay;
  position?: {
    corner: PetCorner;
    marginX: number;
    marginY: number;
  };
}
export interface MotionOptions {
  type: PetRenderMotion;
  loop?: boolean;
  replay?: boolean;
}
export interface MovesConfig {
  default: Record<string, number>;
  actions: MoveSpec[];
}
export interface MoveSpec {
  name: string;
  params?: Record<string, number>;
}
export interface MutteringPlan {
  enabled: boolean;
  petId?: string;
  prompt: string;
  intervalSec: number;
  intervalMs: number;
  image: boolean;
  immediate: boolean;
  duration: number;
}
export interface MutteringPlanInput {
  config?: DshPetConfig | null;
  entry?: DshPetEntry | null;
  enabled?: boolean;
  prompt?: string;
  intervalSec?: number;
  immediate?: boolean;
  image?: boolean;
  duration?: number;
}
export interface PetAnimationInfo {
  name: string;
  once: boolean;
  src: string | null;
  row?: number;
  column?: number;
}
export interface PetBubble {
  id: string;
  title?: ReactNode;
  description?: ReactNode;
  icon?: ReactNode;
  image?: string;
  loading: boolean;
  variant: PetBubbleVariant;
  motion?: MotionInput;
  placement: PetBubblePlacement;
  kind: PetBubbleKind;
  duration: number;
  created: number;
}
export interface PetBubbleHandle {
  (_: PetBubbleOptions): string;
  close: (_?: string) => void;
  clear: () => void;
}
export interface PetBubbleOptions {
  id?: string;
  title?: ReactNode;
  description?: ReactNode;
  icon?: ReactNode;
  image?: string;
  loading?: boolean;
  variant?: PetBubbleVariant;
  motion?: MotionInput;
  timeout?: number;
  placement?: PetBubblePlacement;
  kind?: PetBubbleKind;
}
export interface PetCommonProps extends PetHitboxProps {
  ref?: Ref<PetRef | null>;
  size?: number;
  motion?: MotionInput;
  dragging?: boolean;
  cache?: boolean;
  mirrored?: boolean;
  hidden?: boolean;
  className?: string;
  style?: CSSProperties;
  onMotionChange?: (_: PetRenderMotion) => void;
  onAnimationChange?: (_: PetAnimationInfo | null) => void;
  onReady?: () => void;
  onError?: (_: unknown) => void;
}
export interface PetConfigResult<T> {
  config: T | null;
  error: Error | null;
  loading: boolean;
}
export interface PetHitboxProps {
  hitboxRef?: Ref<HTMLDivElement>;
  onHitboxPointerDown?: (_: PointerEvent<HTMLDivElement>) => void;
  onHitboxPointerUp?: (_: PointerEvent<HTMLDivElement>) => void;
  onHitboxPointerCancel?: (_: PointerEvent<HTMLDivElement>) => void;
}
export interface PetMutteringEvent {
  petId?: string;
  reason: PetMutteringReason;
  intervalSec: number;
  meme?: {
    name: string;
    desc: string;
  };
}
export interface PetMutteringHandle {
  (_: string, _?: PetMutteringShowOptions): void;
  request: () => void;
}
export interface PetMutteringShowOptions {
  image?: string;
  duration?: number;
}
export interface PetProps extends PetCommonProps {
  kind?: 'dsh' | 'codex';
  config: string | PetConfig;
  uri?: string | {
    default: string;
    mac?: string;
  };
  ext?: {
    default: string;
    mac?: string;
  };
  lookAtPointer?: boolean;
  lookDeadzone?: number;
  lookRadius?: number;
  muttering?: boolean;
  mutteringPrompt?: string;
  mutteringIntervalSec?: number;
  mutteringImmediate?: boolean;
  mutteringImage?: boolean;
  mutteringDuration?: number;
  mutteringMotion?: MotionInput;
  onMuttering?: PetMutteringHandler;
}
export interface PetRef {
  motion: (_: MotionInput) => void;
  clear: () => void;
  readonly current: PetRenderMotion;
  bubble: PetBubbleHandle;
  muttering: PetMutteringHandle;
}
export interface PetWeights {
  idle: number;
  turn: number;
  move: number;
}
export interface PhysicsParams {
  gravity: number;
  restitution: number;
  groundFriction: number;
  ceilingBounce: boolean;
  throwPower: number;
  petCollision: boolean;
}
// #endregion

// #region Types
export type AnimationSlot = string | string[];
export type EventSlot = string | string[];
export type Motion = (typeof MOTIONS)[number];
export type MotionInput = PetRenderMotion | MotionOptions;
export type PetBubbleKind = 'bubble' | 'muttering';
export type PetBubblePlacement = 'top' | 'bottom';
export type PetBubbleVariant = 'default' | 'success' | 'warning' | 'danger';
export type PetConfig = DshPetConfig | CodexPetConfig;
export type PetConfigSource = string | PetConfig;
export type PetCorner = 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right';
export type PetDisplay = 'web' | 'desktop' | 'both' | 'none';
export type PetEvents = Record<string, EventSlot[]>;
export type PetMutteringHandler = (_: string, _: PetMutteringEvent) => void;
export type PetMutteringReason = 'baseline' | 'tick' | 'manual';
export type PetRenderMotion = Motion | 'dragging';
// #endregion

// #region Functions
export declare function Pet(_: PetProps): import("react").JSX.Element;
export declare function useConfig<T extends PetConfig>(_: PetConfigSource): PetConfigResult<T>;
export declare function useControllablePet(_?: RefObject<PetRef | null>): PetRef;
// #endregion